name: GNR Debug Patch PRQ Build
on:
  workflow_dispatch:

jobs:
  run-gnr-prq-build:
    runs-on: [self-hosted, Linux, X64, gnr-patch-build]
    env:
      BUILD_PASSWORD: ${{ secrets.BUILD_PASSWORD }}
    steps:
      - name: Run wrapper
        shell: bash
        run: |
          chmod +x /nfs/site/disks/dcsg_0729/users/pkummara/patch_build_wrapper_gnr_prq_debug_gha.sh
          /nfs/site/disks/dcsg_0729/users/pkummara/patch_build_wrapper_gnr_prq_debug_gha.sh
