name: Test Upload SRF INC File

on:
  workflow_dispatch:

jobs:
  upload-srf-inc-test:
    runs-on: [self-hosted, node16]
    steps:
      - name: Basic debug
        shell: bash
        run: |
          set -euxo pipefail
          echo "hello"
          whoami
          pwd
          ls -l /nfs/site/disks/dcsg_0729/patches/SRF/C0/build/83000132/release
