name: Open RealVNC
on: workflow_dispatch
jobs:
  opening-real-vnc:
    runs-on: self-hosted
    steps:
    - name: Opening Real VNC
      run: |
        cd "C:\Program Files\RealVNC\VNC Viewer"
        vncviewer.exe
      shell: cmd
